md "Todos os Paises"
cd "Todos os paises"
md "Argentina" "Bolivia" "Brasil" "Chile" "Colombia" "Equador" "Guiana" "Guiana Francesa" "Paraguai" "Peru" "Suriname" "Uruguai" "Venezuela"
cd "Brasil"
md "Acre" "Alagoas" "Amapa" "Amazonas" "Bahia" "Ceara" "Distrito Federal" "Espirito Santo" "Goias" "Maranhao" "Mato Grosso" "Mato Grosso do Sul" "Minas Gerais" "Parana" "Paraiba" "Para" "Pernambuco" "Piaui" "Rio Grande do Norte" "Rio Grande do Sul" "Rio de Janeiro" "Rondonia" "Roraima" "Santa Catarina" "Sergipe" "Sao Paulo" "Tocantins"
