md "Todos os clubes"
cd "Todos os clubes"
md "Serie A"
md "Serie B"
cd "Serie A"
md "Atletico-MG" "Palmeiras" "Fortaleza" "Bragantino" "Flamengo" "Athletico -PR" "Atletico-GO" "Ceará" "Internacional" "Santos" "Corinthians" "Juventude" "Bahia" "Sao Paulo" "Fluminense" "Cuiabá" "Sport" "America-MG" "Gremio" "Chapecoense" 